[package]
name = "image-preview-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
tera = "1.18"
walkdir = "2.3"
clap = { version = "4.3", features = ["derive"] }
percent-encoding = "2.3"
